create user ZABBIX_MON identified by "";

GRANT CREATE SESSION TO ZABBIX_MON;

GRANT SELECT ON SYS.DBA_DATA_FILES TO ZABBIX_MON;
GRANT SELECT ON SYS.DBA_FREE_SPACE TO ZABBIX_MON;
GRANT SELECT ON SYS.DBA_TABLESPACES TO ZABBIX_MON;
GRANT SELECT ON SYS.DBA_TEMP_FILES TO ZABBIX_MON;
GRANT SELECT ON SYS.DBA_UNDO_EXTENTS TO ZABBIX_MON;
GRANT SELECT ON SYS.DBA_USERS TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$ARCHIVE_DEST TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$ASM_DISKGROUP TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$ASM_DISKGROUP_STAT TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$BACKUP_DATAFILE TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$BACKUP_PIECE TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$BACKUP_SET TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$DATABASE TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$DATAFILE TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$DATAGUARD_STATS TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$DBFILE TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$DIAG_ALERT_EXT TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$INSTANCE TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$LOG TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$MANAGED_STANDBY TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$PROCESS TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$RECOVERY_FILE_DEST TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$SESSION TO ZABBIX_MON;
GRANT SELECT ON SYS.V_$SYSTEM_PARAMETER TO ZABBIX_MON;
